/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f407vg.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(){
	for(uint32_t i=0;i<50000;i++){

	}
}

int main(void)
{
	GPIO_Handle_t LED;

	LED.pGPIOx = GPIOD;

	LED.GPIO_PinConfig.GPIO_PinNumber = 12;
	LED.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	LED.GPIO_PinConfig.GPIO_PinOPType = GPIO_OPTYPE_PP;
	LED.GPIO_PinConfig.GPIO_PinPuPdCtrl = GPIO_PUPD_NOPUPD;
	LED.GPIO_PinConfig.GPIO_PinSpeed = GPIO_OSPEED_MED;

	GPIOD_PClk_EN();
	GPIO_Init(&LED);


	/* Loop forever */
	for(;;){
		GPIO_ToggleOutputPin(LED.pGPIOx, LED.GPIO_PinConfig.GPIO_PinNumber);
		delay();
	}
}
